---
permalink: windows/concept_what_autosupport_is.html 
sidebar: sidebar 
keywords: autosupport, storage, system, backup, operation 
summary: O recurso AutoSupport permite que o servidor SnapManager envie mensagens AutoSupport para o sistema de armazenamento após a conclusão da operação de backup. 
---
= O que é AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso AutoSupport permite que o servidor SnapManager envie mensagens AutoSupport para o sistema de armazenamento após a conclusão da operação de backup.


NOTE: O SnapManager envia mensagens AutoSupport apenas para as operações de backup bem-sucedidas.

Você pode ativar ou desativar o AutoSupport atribuindo os seguintes valores ao parâmetro de configuração auto_support.on no arquivo de configuração smo.config:

* Verdadeiro - ativa o AutoSupport
* False - desativa o AutoSupport



NOTE: Por padrão, o AutoSupport está habilitado no SnapManager.

*Informações relacionadas*

xref:task_adding_storage_systems_to_the_snapmanager_server_host.adoc[Adição de sistemas de storage operando em Clustered Data ONTAP ao host do servidor SnapManager]

xref:task_enabling_autosupport_in_snapmanager.adoc[Ativar o AutoSupport no SnapManager]

xref:task_disabling_autosupport_in_snapmanager.adoc[Desativando o AutoSupport no SnapManager]
