---
permalink: windows/concept_accessing_snapmanager.html 
sidebar: sidebar 
keywords: command-line, interface, cli, graphical, user, gui, accessing 
summary: 'Você pode acessar o SnapManager usando a interface de linha de comando (CLI) ou a interface gráfica do usuário (GUI).' 
---
= Acessando o SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode acessar o SnapManager usando a interface de linha de comando (CLI) ou a interface gráfica do usuário (GUI).

Você pode executar diferentes operações do SnapManager das seguintes maneiras:

* Ao inserir comandos na CLI em um host que está na mesma rede que o host do banco de dados.
+
Para obter uma lista de todos os comandos e uma explicação de suas opções e argumentos, consulte o capítulo Referência de comando.

+
Para acessar a CLI, clique em *Iniciar* > *todos os programas* > *NetApp* > *SnapManager para Oracle* > *Iniciar interface de linha de comando (CLI)*.

* Acessando a GUI em um host na mesma rede que o host do banco de dados.
+
A GUI fornece assistentes simples e fáceis de usar para ajudar você a realizar operações diferentes.



*Informações relacionadas*

xref:concept_snapmanager_for_oraclefor_sap_command_reference.adoc[SnapManager para referência de comando Oracle]
