---
permalink: windows/concept_variables_available_in_the_task_scripts_for_clone_operation.html 
sidebar: sidebar 
keywords: provide, context, information, environment, variable, relate, clone, operation, perform, host 
summary: O SnapManager fornece informações de contexto na forma de variáveis de ambiente relacionadas à operação de clone que está sendo executada. Por exemplo, seu script pode recuperar o nome do host original, o nome do banco de dados clone e o rótulo do backup. 
---
= Variáveis disponíveis nos scripts de tarefa para operação clone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager fornece informações de contexto na forma de variáveis de ambiente relacionadas à operação de clone que está sendo executada. Por exemplo, seu script pode recuperar o nome do host original, o nome do banco de dados clone e o rótulo do backup.

A tabela a seguir lista as variáveis de ambiente que você pode usar em seus scripts:

|===


| Variáveis | Descrição | Formato 


 a| 
SM_ORIGINAL_SID
 a| 
SID da base de dados original
 a| 
cadeia de carateres



 a| 
SM_ORIGINAL_HOST
 a| 
Nome do host associado ao banco de dados original
 a| 
cadeia de carateres



 a| 
SM_ORIGINAL_OS_USER
 a| 
O proprietário do banco de dados original
 a| 
cadeia de carateres



 a| 
SM_ORIGINAL_OS_GROUP
 a| 
GRUPO OS da base de dados original
 a| 
cadeia de carateres



 a| 
SM_TARGET_SID
 a| 
SID do banco de dados clone
 a| 
cadeia de carateres



 a| 
SM_TARGET_HOST
 a| 
Nome de host associado ao banco de dados clone
 a| 
cadeia de carateres



 a| 
SM_TARGET_OS_USER
 a| 
O proprietário do banco de dados clone
 a| 
cadeia de carateres



 a| 
SM_TARGET_OS_GROUP
 a| 
GRUPO OS do banco de dados clone
 a| 
cadeia de carateres



 a| 
SM_TARGET_DB_PORT
 a| 
Porta do banco de dados de destino
 a| 
número inteiro



 a| 
SM_TARGET_GLOBAL_DB_NAME
 a| 
Nome do banco de dados global do banco de dados de destino
 a| 
cadeia de carateres



 a| 
SM_BACKUP_LABEL
 a| 
Etiqueta do backup usado para o clone
 a| 
cadeia de carateres

|===