---
permalink: windows/concept_general_layout_and_configuration.html 
sidebar: sidebar 
keywords: general, layout, configuration, information, storage, disk, group 
summary: Você pode encontrar informações sobre os layouts gerais de banco de dados recomendados e configurações de armazenamento para evitar problemas relacionados a grupos de discos, tipos de arquivos e espaços de tabela. 
---
= Layout e configuração gerais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode encontrar informações sobre os layouts gerais de banco de dados recomendados e configurações de armazenamento para evitar problemas relacionados a grupos de discos, tipos de arquivos e espaços de tabela.

* Não inclua arquivos de mais de um tipo de sistema de arquivos SAN em seu banco de dados.
+
Todos os arquivos que compõem um banco de dados devem residir no mesmo tipo de sistema de arquivos.

* O SnapManager requer vários tamanhos de bloco de 4K KB.
* Se você deseja Registrar backups do SnapManager com o Oracle Recovery Manager (RMAN), você deve criar perfis habilitados para RMAN.


A seguir estão algumas diretrizes para separação de volumes:

* Os arquivos de dados para apenas um banco de dados devem estar no volume.
* Você deve usar volumes separados para cada uma das seguintes classificações de arquivos: Binários de banco de dados, arquivos de dados, arquivos de log refazer on-line, arquivos de log refazer arquivados e arquivos de controle.
* Você não precisa criar um volume separado para arquivos temporários de banco de dados, porque o SnapManager não faz backup de arquivos temporários de banco de dados.


Para obter mais informações, consulte _SnapManager para melhores práticas Oracle_.

*Informações relacionadas*

http://media.netapp.com/documents/tr-3761.pdf["Melhores práticas do SnapManager para Oracle: Media.NetApp.com/Documents/tr-3761.pdf"]
