---
permalink: windows/concept_collecting_additional_log_information_for_easier_debugging.html 
sidebar: sidebar 
keywords: collect, additional, log, information, debug, fail, external, environment 
summary: Se você precisar de logs adicionais para depurar uma operação SnapManager com falha, você deve definir uma variável de ambiente externo Server.log.level. Esta variável substitui o nível de log padrão e despeja todas as mensagens de log no arquivo de log. Por exemplo, você pode alterar o nível de log para DEBUG, que Registra mensagens adicionais e pode ajudar em problemas de depuração. 
---
= Coletar informações de log adicionais para facilitar a depuração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você precisar de logs adicionais para depurar uma operação SnapManager com falha, você deve definir uma variável de ambiente externo Server.log.level. Esta variável substitui o nível de log padrão e despeja todas as mensagens de log no arquivo de log. Por exemplo, você pode alterar o nível de log para DEBUG, que Registra mensagens adicionais e pode ajudar em problemas de depuração.

Os logs do SnapManager podem ser encontrados nos seguintes locais:

* SnapManager_install_Directory


Para substituir o nível de log padrão, você deve executar as seguintes etapas:

. Crie um arquivo de texto Platform.override no diretório de instalação do SnapManager.
. Adicione o parâmetro Server.log.level no arquivo de texto Platform.override.
. Atribua um valor (RASTREAMENTO, DEPURAÇÃO, INFORMAÇÕES, AVISO, ERRO, FATAL ou PROGRESSO) ao parâmetro Server.log.level.
+
Por exemplo, para alterar o nível de log para ERRO, defina o valor de Server.log.level como ERRO.

+
Server.log.level.ERROR

. Reinicie o servidor SnapManager.



NOTE: Se as informações de log adicionais não forem necessárias, você pode excluir o parâmetro Server.log.level do arquivo de texto Platform.override.

O SnapManager gerencia o volume de arquivos de log do servidor com base nos valores definidos pelo usuário dos seguintes parâmetros no arquivo smo.config:

* log.max_log_files
* log.max_log_file_size
* log.max_rolling_operation_factory_logs

