---
permalink: windows/concept_preparing_to_upgrade_snapmanager_for_oracle.html 
sidebar: sidebar 
keywords: environment, software, hardware, browser, database, operating, system, preparing 
summary: O ambiente no qual você deseja atualizar o SnapManager deve atender aos requisitos específicos de software, hardware, navegador, banco de dados e sistema operacional. Para obter as informações mais recentes sobre os requisitos, consulte a Matriz de interoperabilidade. 
---
= Preparando-se para atualizar o SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ambiente no qual você deseja atualizar o SnapManager deve atender aos requisitos específicos de software, hardware, navegador, banco de dados e sistema operacional. Para obter as informações mais recentes sobre os requisitos, consulte a Matriz de interoperabilidade.

Você deve garantir que você execute as seguintes tarefas antes de atualizar:

* Conclua as tarefas de pré-instalação necessárias.
* Baixe o pacote de instalação mais recente do SnapManager para Oracle.
* Instale e configure a versão apropriada do SnapDrive para Windows em todos os hosts de destino.
* Crie um backup do banco de dados existente do SnapManager para repositório Oracle.


http://support.netapp.com/NOW/products/interoperability/["Matriz de interoperabilidade: Support.NetApp.com/NOW/Products/Interoperability"]
