---
permalink: windows/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: Informações sobre marcas comerciais 
---
= Informações sobre marcas comerciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, Arch Design, ASUP, AutoSupport, Campaign Express, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Fueled by SolidFire, GetSuccessful, Helix Design, LockVault, Manage ONTAP, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect SnapRestore, Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud e WAFL , entre outros nomes, são marcas comerciais ou marcas registradas da NetApp, Inc., nos Estados Unidos e/ou em outros países. Todas as outras marcas ou produtos são marcas comerciais ou marcas registradas de seus respectivos proprietários e devem ser tratados como tal. Uma lista atual de marcas registradas da NetApp está disponível na web.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
