---
permalink: windows/reference_the_smosmsap_notification_set_command.html 
sidebar: sidebar 
keywords: notification, set, command, configure, mail, server, smo 
summary: Você pode usar o comando Notification set para configurar o servidor de e-mail. 
---
= O comando smo notification set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o comando Notification set para configurar o servidor de e-mail.



== Sintaxe

[listing]
----

        smo notification set
-sender-email email_address
-mailhost mailhost
-mailport mailport
[-authentication
-username username
-password password]
-repository
-dbname repo_service_name
-port repo_port]
-host repo_host
-login -username repo_username
[-quiet | -verbose]
----


== Parâmetros

* *-sender-email_address*
+
Especifica o endereço de e-mail do remetente a partir do qual os alertas de e-mail são enviados. No SnapManager 3,2 para Oracle, você pode incluir um hífen (-) ao especificar o nome de domínio do endereço de e-mail. Por exemplo, você pode especificar o endereço de e-mail do remetente como -sender-email07lbfmdatacenter@continental-corporation.com.

* *-mailhost mailhost*
+
Especifica o nome ou endereço IP do servidor host que manipula notificações de e-mail.

* *-mailport mailport*
+
Especifica o número da porta do servidor de correio.

* *-authentication -username username -password*
+
Especifica os detalhes de autenticação para o endereço de e-mail. Tem de especificar o nome de utilizador e a palavra-passe.

* *-repositório*
+
Especifica os detalhes do banco de dados do repositório.

* *-port repo_port*
+
Especifica o número da porta TCP (Transmission Control Protocol) usada para acessar o banco de dados do repositório.

* *-dbname repo_service_name*
+
Especifica o nome do banco de dados do repositório. Você pode usar o nome global ou o identificador do sistema.

* *-host repo_host*
+
Especifica o nome ou endereço IP do host onde reside o banco de dados do repositório.

* *-login*
+
Especifica os detalhes de login do repositório. Isso é opcional. Se não for especificado, o SnapManager padrão será o modo de conexão de autenticação do sistema operacional.

* *-username repo_username*
+
Especifica o nome de usuário necessário para acessar o banco de dados do repositório.

* *-silencioso*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo

O exemplo a seguir configura o servidor de e-mail:

[listing]
----
smo notification set -sender-email admin@org.com -mailhost hostname.org.com -mailport 25 authentication -username davis -password davis -repository -port 1521 -dbname SMOREPO -host hotspur
-login -username grabal21 -verbose
----