---
permalink: windows/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, credentials, particular, secured, resource, smo 
summary: Este comando exclui as credenciais do usuário para um determinado recurso protegido. 
---
= O comando smo Credential delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este comando exclui as credenciais do usuário para um determinado recurso protegido.



== Sintaxe

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== Parâmetros

* *-host hostname*
+
Especifica o nome do servidor host no qual o SnapManager está sendo executado.

+
O parâmetro -host inclui as seguintes opções:

+
** -Name host_name: Especifica o nome do host para o qual você excluirá a senha.
** -Username user_name: Especifica o nome de usuário no host.


* *-repositório -dbname*
+
Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.

+
O parâmetro -repositório inclui as seguintes opções:

+
** -Dbnamepo_Service_name: Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.
** -Host repo_host: Especifica o nome ou endereço IP do servidor host no qual o banco de dados do repositório é executado.
** -Login-username repo_username: Especifica o nome de usuário necessário para acessar o banco de dados que armazena o repositório.
** -Port repo_port: Especifica o número da porta TCP usado para acessar o banco de dados que armazena o repositório.


* *-profile -name profile_name*
+
Especifica o perfil ao qual o banco de dados está associado.

+
O parâmetro -profile inclui a seguinte opção:

+
** -Nome profilename: Especifica o nome do perfil para o qual você excluirá a senha.


* *-silencioso*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo de comando

Este exemplo exclui as credenciais do perfil.

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
Este exemplo exclui as credenciais do repositório.

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
Este exemplo exclui as credenciais do host.

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
*Informações relacionadas*

xref:task_deleting_credentials_for_individual_resources.adoc[Exclusão de credenciais para recursos individuais]
