---
permalink: windows/reference_troubleshooting_known_issues.html 
sidebar: sidebar 
keywords: known, issues, snapmanager, troubleshooting 
summary: Você deve estar ciente de alguns problemas conhecidos que podem ocorrer quando você usa o SnapManager e como trabalhar em torno deles. 
---
= Solução de problemas conhecidos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente de alguns problemas conhecidos que podem ocorrer quando você usa o SnapManager e como trabalhar em torno deles.



== O SnapManager para Oracle não consegue identificar perfis de modo de cluster

Se o nome do perfil do modo de cluster não estiver presente no arquivo cmode_profiles.config no diretório de instalação do SnapManager para Oracle, a seguinte mensagem de erro pode ser acionada:

Configure o servidor DFM usando o SnapDrive config set -dfm user_name Appliance_name.

Além disso, ao atualizar o SnapManager para Oracle, se você excluir a pasta /opt/NetApp/smo/*, o arquivo cmode_profiles.config que tem os nomes de perfil do modo cluster também será excluído. Esse problema também aciona a mesma mensagem de erro.

*Solução alternativa*

Atualizar o perfil: <profile_name> perfil de atualização do perfil smo


NOTE: Se o SnapManager for Oracle estiver instalado no caminho /opt/NetApp/smo/, a localização do arquivo será /opt/NetApp/smo/cmode_profile/cmode_profiles.config.



== O servidor não consegue iniciar

Ao iniciar o servidor, você pode ver uma mensagem de erro semelhante à seguinte:

SMO-01104: Erro ao invocar o comando: SMO-17107: O servidor SnapManager falhou ao iniciar na porta 8074 devido aos seguintes erros: java.net.BindException: Endereço já em uso

Isso pode ser porque as portas de escuta SnapManager (27214 e 27215, por padrão) estão atualmente em uso por outro aplicativo.

Esse erro também pode ocorrer se o comando smo_Server já estiver em execução, mas o SnapManager não deteta o processo existente.

*Solução alternativa*

Você pode reconfigurar o SnapManager ou o outro aplicativo para usar portas diferentes.

Para reconfigurar o SnapManager, edite o seguinte arquivo: C: Arquivos de programas/NetApp/SnapManager para as propriedades/smo.config

Você atribui os seguintes valores:

* SMO Server.port.27214
* SMO Server.rmiRegistry.port.27215
* remote.registry.ocijdbc.port 27215
+
O Remote.registry.ocijdbc.port deve ser o mesmo que Server.rmiRegistry.port.



Para iniciar o servidor SnapManager, execute as seguintes etapas:

. Clique em *Iniciar* > *Painel de controlo* > *Ferramentas administrativas* > *Serviços*.
. Você pode iniciar o servidor de uma de três maneiras:
+
** No painel esquerdo, clique em *Iniciar*.
** Clique com o botão direito do Mouse em NetApp SnapManager 3,3 para Oracle e selecione *Iniciar* no menu suspenso.
** Clique duas vezes em NetApp SnapManager 3,3 para Oracle e na janela Propriedades que se abre, clique em *Iniciar*.






== Não é possível gerenciar nomes de destino do arquivo de log se os nomes de destino forem parte de outros nomes de destino

Durante a criação de uma cópia de segurança do registo de arquivo, se o utilizador excluir um destino que faz parte de outros nomes de destino, os outros nomes de destino também serão excluídos.

Por exemplo, suponha que existem três destinos disponíveis para serem excluídos: E: Arch, G: Arch e H: Arch. Ao criar o backup do arquivo de log de arquivo, se você excluir e: ''arch usando o comando

[listing]
----
smo backup create -profile almsamp1 -data -online -archivelogs  -exclude-dest E:\\arch
----
, SnapManager para Oracle exclui todos os destinos começando com e: '' arch.

*Solução alternativa*

* Adicione um separador de caminho depois que os destinos são configurados em arquivo_dest. Por exemplo, altere o e: ''arch'' para e: ''arch'''.
* Ao criar um backup, inclua destinos em vez de excluir qualquer destino.




== O tamanho do banco de dados do repositório cresce com o tempo e não com o número de backups

O tamanho do banco de dados do repositório cresce com o tempo porque as operações do SnapManager inserem ou excluem dados dentro do esquema nas tabelas do banco de dados do repositório, o que resulta em alto uso de espaço de índice.

*Solução alternativa*

Você deve monitorar e reconstruir os índices de acordo com as diretrizes da Oracle para controlar o espaço consumido pelo esquema do repositório.



== A GUI do SnapManager não pode ser acessada e as operações do SnapManager falham quando o banco de dados do repositório está inativo

As operações do SnapManager falham e você não pode acessar a GUI quando o banco de dados do repositório está inativo.

A tabela a seguir lista as diferentes ações que você pode querer executar e suas exceções:

|===


| Operações | Exceções 


 a| 
Abrindo um repositório fechado
 a| 
A seguinte mensagem de erro é registrada em SM_GUI.log: [WARN ]: SMO-01106: Ocorreu um erro ao consultar o repositório: Conexão fechada java.sql.SQLException: Conexão fechada.



 a| 
Atualizando um repositório aberto pressionando F5
 a| 
Uma exceção de repositório é exibida na GUI e também Registra uma NullPointerException no arquivo sm_gui.log.



 a| 
Atualizando o servidor host
 a| 
Uma NullPointerException é registrada no arquivo sumo_gui.log.



 a| 
Criando um novo perfil
 a| 
Uma NullPointerException é exibida na janela Profile Configuration (Configuração do perfil).



 a| 
Atualizando um perfil
 a| 
A seguinte exceção SQL é registrada em SM_GUI.log: [WARN ]: SMO-01106: Ocorreu um erro ao consultar o repositório: Conexão fechada.



 a| 
Aceder a uma cópia de segurança
 a| 
A seguinte mensagem de erro é registrada em SM_GUI.log: Falha ao inicializar lazily uma coleção.



 a| 
Exibindo propriedades de clone
 a| 
A seguinte mensagem de erro é registrada em sm_gui.log e sumo_GUI.log: Falha ao inicializar lazily uma coleção.

|===
*Solução alternativa*

Você deve garantir que o banco de dados do repositório esteja sendo executado quando quiser acessar a GUI ou executar quaisquer operações do SnapManager.



== Não é possível criar arquivos temporários para o banco de dados clonado

Quando os arquivos temporários de espaço de tabela do banco de dados de destino são colocados em pontos de montagem diferentes do ponto de montagem dos arquivos de dados, a operação de criação de clone é bem-sucedida, mas o SnapManager não consegue criar arquivos temporários para o banco de dados clonado.

*Solução alternativa*

Você deve executar um dos seguintes procedimentos:

* Certifique-se de que o banco de dados de destino é definido de modo que os arquivos temporários sejam colocados no mesmo ponto de montagem que o dos arquivos de dados.
* Crie ou adicione manualmente arquivos temporários no banco de dados clonado.




== O backup do banco de dados do Data Guard Standby falha

Se qualquer local de registo de arquivo estiver configurado com o nome de serviço da base de dados principal, a cópia de segurança da base de dados em espera do Data Guard falha.

*Solução alternativa*

Na GUI, você deve limpar *especificar local de Registro de arquivo externo* correspondente ao nome do serviço do banco de dados principal.
