---
permalink: windows/reference_the_smosmsapclone_delete_command.html 
sidebar: sidebar 
keywords: run, clone, delete, command, operation, smo 
summary: Você pode executar o comando clone delete para excluir um clone. Você não pode excluir um clone se o clone for usado por qualquer operação. 
---
= O comando smo clone delete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o comando clone delete para excluir um clone. Você não pode excluir um clone se o clone for usado por qualquer operação.



== Sintaxe

[listing]
----

        smo clone delete
-profile profile_name
\[-id guid \| -label clone_name\]
[-login
\[-username db_username -password db_password -port db_port\]
 ]
\[-syspassword syspassword\]
-force
\[-dump\]
\[-quiet \| -verbose\]
----


== Parâmetros

* *-profile profile_name*
+
Especifica o nome do perfil que contém o clone que está sendo excluído. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *-força*
+
Exclui o clone mesmo que haja recursos associados ao clone.

* *-id guid*
+
Especifica o GUID para o clone que está sendo excluído. O GUID é gerado pelo SnapManager quando você cria um clone. Você pode usar o comando smo clone list para exibir o GUID para cada clone.

* *-nome da etiqueta*
+
Especifica o rótulo para o clone que está sendo excluído.

* *-syspassword syspassword*
+
Especifica a senha para o usuário privilegiado do sistema.

+

NOTE: Você deve fornecer a senha para o usuário privilegiado do sistema se as credenciais do banco de dados fornecidas não forem as mesmas para o usuário privilegiado do sistema.

* *-login*
+
Permite-lhe introduzir os detalhes de início de sessão da base de dados.

* *-username db_username*
+
Especifica o nome de usuário necessário para acessar o banco de dados.

* *-password db_password*
+
Especifica a senha necessária para acessar o banco de dados.

* *-port db_port*
+
Especifica o número da porta TCP usado para acessar o banco de dados descrito pelo perfil.

* *-dump*
+
Especifica para coletar os arquivos de despejo após a operação de exclusão do clone.

* *-silencioso*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo

O exemplo a seguir exclui o clone:

[listing]
----
smo clone delete -profile SALES1 -label SALES_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----