---
permalink: windows/reference_the_smosmsap_operation_show_command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, profile, smo, host 
summary: 'Você pode executar o comando operation show para listar as informações resumidas de todas as operações realizadas com o perfil especificado. A saída lista o usuário cliente (o usuário para o PC cliente) e o usuário efetivo (o usuário no SnapManager que é válido no host selecionado).' 
---
= O comando smo operation show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o comando operation show para listar as informações resumidas de todas as operações realizadas com o perfil especificado. A saída lista o usuário cliente (o usuário para o PC cliente) e o usuário efetivo (o usuário no SnapManager que é válido no host selecionado).



== Sintaxe

[listing]
----

        smo operation show
-profile profile_name
\[-label label \| -id id\]
\[-quiet \| -verbose\]
----


== Parâmetros

* *-profile profile_name*
+
Especifica o nome do perfil. Esse nome pode ter até 30 carateres e deve ser único dentro do host.

* * etiqueta de etiqueta*
+
Especifica o rótulo para a operação.

* *-id id*
+
Especifica o identificador para a operação.

* *-silencioso*
+
Opcional: Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Opcional: Exibe mensagens de erro, aviso e informativas no console.





== Exemplo

A linha de comando a seguir mostra informações detalhadas sobre uma operação:

[listing]
----
# smo operation show -profile myprofile -id ff8080811295eb1c011295eb28230001
----
[listing]
----
Operation Attempted
   Operation ID: ff8080811295eb1c011295eb28230001
   Type:RestoreFor profile: myprofile
   With Force: No
   Performed on backup
   Operation ID: ff8080811295eb1c011296eb23290001
   Label: mylabel
Operation Runtime Information
   Status: SUCCESS
   Start date: 2007-07-16 13:24:09 IST
   End date: 2007-07-16 14:10:10 IST
   Client user: amorrow
   Effective user: amorrow
Host
   Host Run upon: Host3
   Process ID: 3122
   SnapManager version: 3.3
Repository
   Connection: user1@SMOREPO/hotspur:1521
   Repository version: 3.3
Resources in use
   Volume:
     ssys1:/vol/luke_ES0_0 (FlexClone)
   Filesystems:C:\\SnapManager_auto_mounts\\O-20120712052511170_0
----
*Informações relacionadas*

xref:task_viewing_operation_details.adoc[Visualização dos detalhes da operação]
