---
permalink: windows/task_using_post-processing_task_specification_to_mirror_volumes.html 
sidebar: sidebar 
keywords: snapmanager, oracle, enable, script, mirror, volume, backup, operation, occur, windows, environment, post-processing, task, specification 
summary: O SnapManager para Oracle permite que você use o script para espelhar os volumes após a operação de backup ocorrer em um ambiente Windows. 
---
= Usando a especificação de tarefa de pós-processamento para espelhar volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager para Oracle permite que você use o script para espelhar os volumes após a operação de backup ocorrer em um ambiente Windows.

. Crie um arquivo XML de especificação de tarefa.
. No arquivo XML, insira o nome do script como um parâmetro de entrada.
. Salve o arquivo XML de especificação de tarefa.
. Crie um backup protegido do banco de dados para o armazenamento secundário usando o seguinte comando.
+
Ao criar o backup protegido, você deve fornecer o caminho completo do arquivo XML de especificação de tarefa salva após a opção -taskspecc.

+
Exemplo: Smubackup create -profile test_profile -full -online -tasksc "C: Mirror' SnapMirror.xml"



O exemplo a seguir mostra uma estrutura de especificação de tarefa de pós-processamento se você estiver usando o Data ONTAP operando no modo 7:

[listing]
----
#     <post-tasks>
#               <task>
#                   <name>Mirror the backup</name>
#                    <description>Mirror the backup</description>
#               </task>
#             <post-tasks>
----
O exemplo a seguir mostra uma estrutura de especificação de tarefa de pós-processamento se você estiver usando o Clustered Data ONTAP:

[listing]
----
# <task-specification>
#              <post-tasks>
#                  <task>
#                   <name>"Vault the backup for cDOT"</name>
#                    <parameter>
#                    <name>SNAPSHOT_LABEL</name>
#                   <value>TST</value>
#                    </parameter>
#                  </task>
#                </post-tasks>
#              </task-specification>
#            </preposttask-specification>
----