---
permalink: windows/task_starting_the_snapmanager_graphical_user_interface.html 
sidebar: sidebar 
keywords: snapmanager, install, host, graphical, user, interface, gui, program, start 
summary: 'Se o SnapManager estiver instalado no host, inicie a interface gráfica do usuário (GUI) do SnapManager selecionando o programa em uma lista de programas.' 
---
= Iniciando a GUI do SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o SnapManager estiver instalado no host, inicie a interface gráfica do usuário (GUI) do SnapManager selecionando o programa em uma lista de programas.

* Certifique-se de que o servidor SnapManager foi iniciado.


Você pode iniciar a GUI do SnapManager de uma das seguintes maneiras:

* No host SnapManager, clique em *Iniciar* > *todos os programas* > *NetApp* > *SnapManager para Oracle* > *Iniciar GUI SMO*.
* Se o SnapManager não estiver instalado no host, use o Java Web Start, que faz o download dos componentes do SnapManager e inicia a GUI.


*Informações relacionadas*

xref:task_downloading_and_starting_the_graphical_user_interface_using_java_web_start_windows.adoc[Baixando e iniciando a interface gráfica do usuário usando o Java Web Start]
