---
permalink: windows/task_customizing_e_mail_subject_for_a_new_profile.html 
sidebar: sidebar 
keywords: customize, email, subject, new, profile, create, customizing 
summary: Você pode personalizar o assunto do e-mail para o novo perfil ao criá-lo. 
---
= Personalizar o assunto do e-mail para um novo perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode personalizar o assunto do e-mail para o novo perfil ao criá-lo.

Você pode personalizar o assunto do e-mail usando o padrão dB-sid__host_dB-date____start-date_end-date_____status ou digite seu próprio texto.

|===


| Nome da variável | Descrição | Exemplo de valor 


 a| 
perfil
 a| 
Nome do perfil usado para a operação do banco de dados
 a| 
PROF1



 a| 
nome da operação
 a| 
Nome da operação do banco de dados
 a| 
Cópia de segurança, cópia de segurança de dados, cópia de segurança de dados e registos de arquivo



 a| 
db-sid
 a| 
SID do banco de dados
 a| 
DB1



 a| 
db-host
 a| 
Nome do servidor anfitrião
 a| 
HostA



 a| 
data de início
 a| 
Hora de início da operação do banco de dados no formato mmdd:hh:ss aaaa
 a| 
Abril 27 21:00:45 PST 2012



 a| 
data de fim
 a| 
Hora de fim da operação do banco de dados no formato mmdd:hh:ss aaaa
 a| 
Abril 27 21:10:45 PST 2012



 a| 
estado
 a| 
Estado da operação da base de dados
 a| 
Sucesso

|===
Se você não fornecer nenhum valor para as variáveis, o SnapManager exibirá a seguinte mensagem de erro: Valor(s) ausente(s) -Assunto.

. Digite o seguinte comando: smo profile create -profileprofile [-profile-passwordprofile_password] -repositório-dbnamepo_Service_name-hostrepo_host-portrepo_port address1 address2 address1 address2

