---
permalink: windows/task_clearing_user_credentials_for_all_hosts_repositories_and_profiles.html 
sidebar: sidebar 
keywords: clear, cache, credentials, resource, host, resource, profile, delete 
summary: 'Você pode limpar o cache de suas credenciais para recursos (hosts, repositórios e perfis). Isso exclui todas as credenciais de recurso para o usuário que executa o comando. Depois de limpar o cache, você deve autenticar suas credenciais novamente para obter acesso a esses recursos protegidos.' 
---
= Limpando credenciais de usuário para todos os hosts, repositórios e perfis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode limpar o cache de suas credenciais para recursos (hosts, repositórios e perfis). Isso exclui todas as credenciais de recurso para o usuário que executa o comando. Depois de limpar o cache, você deve autenticar suas credenciais novamente para obter acesso a esses recursos protegidos.

. Para limpar suas credenciais, digite o comando smo Credential Clear na CLI do SnapManager ou selecione *Admin* > *Credentials* > *Clear Cache* na GUI do SnapManager.
. Saia da GUI do SnapManager.
+
NOTA:

+
** Se você limpou o cache de credenciais da GUI do SnapManager, não será necessário sair da GUI do SnapManager.
** Se você limpou o cache de credenciais da CLI do SnapManager, reinicie a GUI do SnapManager.
** Se você tiver excluído o arquivo de credenciais criptografadas manualmente, será necessário reiniciar a GUI do SnapManager novamente.


. Para definir as credenciais novamente, repita o processo para definir credenciais para o repositório, host de perfil e perfil. Para obter informações adicionais sobre como definir novamente as credenciais do usuário, consulte "Definir credenciais após limpar o cache de credenciais".


*Informações relacionadas*

xref:reference_the_smosmsapcredential_clear_command.adoc[O comando smo Credential Clear]
