---
permalink: windows/task_disabling_email_notification_for_multiple_profiles.html 
sidebar: sidebar 
keywords: enable, summary, email, notification, profile, disable, longer, receive, alert, disabling 
summary: Depois de ativar a notificação de resumo por e-mail para vários perfis, você pode desativá-los para não receber mais alertas de e-mail. 
---
= Desativar a notificação de e-mail para vários perfis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de ativar a notificação de resumo por e-mail para vários perfis, você pode desativá-los para não receber mais alertas de e-mail.

O SnapManager permite desativar a notificação de e-mail de resumo para as operações de banco de dados executadas por perfil. Na CLI do SnapManager, digite o comando de notificação remove-summary-notification para desativar a notificação de e-mail de resumo para vários perfis e o nome do banco de dados do repositório para o qual você não precisa de notificação por e-mail.

. Para desativar a notificação de resumo para vários perfis em um banco de dados de repositório, digite o seguinte comando: smo notification remove-summary-notification -repositório-portrepo_port-dbnamepo_Service_name-hostrepo_host-login-usernamepo_username


O exemplo a seguir mostra a notificação de resumo sendo desativada para vários perfis em um banco de dados de repositório:

[listing]
----

smo notification remove-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5
----