---
permalink: unix-administration/concept_restoring_database_backup.html 
sidebar: sidebar 
keywords: snapmanager, oracle, restore, database, snapshot, file-based, backup, scn, local 
summary: 'O SnapManager para Oracle permite restaurar um banco de dados para o estado em que estava quando uma cópia Snapshot foi tirada. Além do processo de restauração baseado em arquivo, o SnapManager oferece suporte à tecnologia de restauração rápida baseada em volume, o que reduz o tempo de restauração significativamente em comparação com outros métodos de recuperação. Como os backups são criados com mais frequência, o número de logs que precisam ser aplicados é reduzido, reduzindo assim o tempo médio de recuperação (MTTR) para um banco de dados.' 
---
= Restaurando backups de bancos de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager para Oracle permite restaurar um banco de dados para o estado em que estava quando uma cópia Snapshot foi tirada. Além do processo de restauração baseado em arquivo, o SnapManager oferece suporte à tecnologia de restauração rápida baseada em volume, o que reduz o tempo de restauração significativamente em comparação com outros métodos de recuperação. Como os backups são criados com mais frequência, o número de logs que precisam ser aplicados é reduzido, reduzindo assim o tempo médio de recuperação (MTTR) para um banco de dados.

A seguir estão algumas das tarefas que você pode executar relacionadas à restauração e recuperação de dados em bancos de dados:

* Execute um repositório baseado em arquivo ou uma restauração baseada em volume, que é o método mais rápido de restaurar backups de banco de dados e é o padrão usado pelo SnapManager.
* Restaure todo o backup ou uma parte dele.
+
Se você restaurar uma parte dele, especifique um grupo de espaços de tablespaces ou um grupo de arquivos de dados. Você também pode restaurar os arquivos de controle juntamente com os dados ou apenas os arquivos de controle.

* Recupere os dados com base em um ponto no tempo ou em todos os logs disponíveis, que armazena a última transação comprometida com o banco de dados.
+
O ponto no tempo pode ser um número de alteração do sistema Oracle (SCN) ou uma data e hora (aaaa-mm-dd:hh:mm:ss). O SnapManager utiliza o relógio de 24 horas.

* Restauração a partir de backups no storage primário (backups locais).
* Restaure e recupere o backup usando o SnapManager, ou use o SnapManager para restaurar o backup e use outra ferramenta, como o Gerenciador de recuperação (RMAN), para recuperar os dados.
* Restaure backups de locais alternativos.
* Restaure backups protegidos do storage secundário (backups remotos) e de um local alternativo usando o arquivo de especificação de restauração.


Você pode restaurar um backup feito por uma versão anterior do SnapManager usando o SnapManager 3,0 e versões posteriores.

O SnapManager também permite restaurar bancos de dados de gerenciamento automático de storage (ASM). Um grupo de discos ASM pode ser compartilhado por vários bancos de dados. Portanto, não é possível reverter para uma cópia Snapshot mais antiga do grupo de discos, pois ela reverteria todos os bancos de dados. As soluções tradicionais de operação de restauração passam pelo host e exigem que todos os blocos que constituem o banco de dados sejam movidos do sistema de storage para o host e, em seguida, de volta para o sistema de storage. O SnapManager alivia essa sobrecarga, fornecendo a capacidade de restaurar apenas os dados necessários no grupo de discos ASM sem passar pelo host.

Os administradores podem executar operações de restauração ou recuperação usando a interface gráfica do usuário (GUI) do SnapManager ou usando a interface de linha de comando (CLI).

*Informações relacionadas*

xref:concept_database_backup_management.adoc[Fazer backup de bancos de dados]

xref:reference_the_smosmsapbackup_restore_command.adoc[O comando smo backup restore]
