---
permalink: unix-administration/concept_restore_process_identification.html 
sidebar: sidebar 
keywords: restore, process, support, snapmanager, oracle, file-based, backup 
summary: Todos os processos de restauração não são suportados em todas as versões do SnapManager para Oracle. Depois de atualizar o SnapManager, você precisa estar ciente do processo de restauração que você pode usar para restaurar um backup. 
---
= Restaurar tipos de processo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Todos os processos de restauração não são suportados em todas as versões do SnapManager para Oracle. Depois de atualizar o SnapManager, você precisa estar ciente do processo de restauração que você pode usar para restaurar um backup.

Os backups criados usando o SnapManager 3,0 ou posterior podem ser restaurados usando processos de restauração rápida e baseados em arquivos. No entanto, os backups criados usando uma versão anterior ao SnapManager 3,0 podem ser restaurados usando apenas o processo de restauração baseado em arquivo.

Você pode determinar a versão do SnapManager usada para criar o backup executando o comando -backup show.

*Informações relacionadas*

xref:concept_what_database_restore_is.adoc[Qual é a restauração do banco de dados]
