---
permalink: unix-administration/concept_considerations_for_cloning_a_database_to_an_alternate_host.html 
sidebar: sidebar 
keywords: clone, host, database, reside, requirement, consideration, alternate, oracle 
summary: Antes de poder clonar para um host diferente daquele em que o banco de dados reside, há alguns requisitos que precisam ser atendidos. 
---
= Considerações para clonar um banco de dados para um host alternativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder clonar para um host diferente daquele em que o banco de dados reside, há alguns requisitos que precisam ser atendidos.

A tabela a seguir mostra os requisitos de configuração do host de origem e destino:

|===
| Pré-requisito configurado | Requisito 


 a| 
Arquitetura
 a| 
Deve ser o mesmo nos hosts de origem e destino



 a| 
Sistema operativo e versão
 a| 
Deve ser o mesmo nos hosts de origem e destino



 a| 
SnapManager para Oracle
 a| 
Deve ser instalado e executado nos hosts de origem e destino



 a| 
Credenciais
 a| 
Deve ser definido para que o usuário acesse o host de destino



 a| 
Oracle
 a| 
A mesma versão de software deve ser instalada nos hosts de origem e destino.

O Oracle Listener deve estar em execução no host de destino.



 a| 
Pilha de storage compatível
 a| 
Deve ser o mesmo nos hosts de origem e destino



 a| 
Protocolo usado para acessar arquivos de dados
 a| 
Deve ser o mesmo nos hosts de origem e destino



 a| 
Gerentes de volume
 a| 
Deve ser configurado tanto nos hosts de origem quanto de destino e deve ser de versões compatíveis

|===
Você também pode clonar um banco de dados de gerenciamento automático de storage (ASM) em um host remoto. Ao fazer isso, você deve garantir que a instância ASM esteja sendo executada no host remoto.
