---
permalink: unix-administration/concept_volume_management_restrictions.html 
sidebar: sidebar 
keywords: snapmanager, volume, management, restriction, environment, asm, disk, group, linux 
summary: O SnapManager tem certas restrições de gerenciamento de volumes que podem afetar seu ambiente. 
---
= Restrições de gerenciamento de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager tem certas restrições de gerenciamento de volumes que podem afetar seu ambiente.

Você pode ter vários grupos de discos para um banco de dados; no entanto, as seguintes limitações se aplicam a todos os grupos de discos para um determinado banco de dados:

* Os grupos de discos para o banco de dados podem ser gerenciados por apenas um gerenciador de volumes.
* Dispositivos brutos suportados por um gerenciador de volumes lógico não são suportados para proteção de dados Oracle.
+
Os grupos de discos de storage bruto de dispositivos e gerenciamento automático de storage (ASM) devem ser provisionados diretamente em dispositivos físicos. Em alguns casos, o particionamento é necessário.

* Um ambiente Linux sem gerenciamento lógico de volume requer uma partição.

