---
permalink: unix-administration/concept_what_cloning_is.html 
sidebar: sidebar 
keywords: clone, database, replica, original, database, clone, full, backup, current, system, dlexclone, snapmanager 
summary: Você pode clonar um banco de dados para criar uma réplica exata do banco de dados original. Você pode criar o clone a partir de um backup completo ou do estado atual do banco de dados. 
---
= O que é Clonagem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode clonar um banco de dados para criar uma réplica exata do banco de dados original. Você pode criar o clone a partir de um backup completo ou do estado atual do banco de dados.

Algumas das vantagens de criar um clone usando o SnapManager são as seguintes:

|===
| Vantagens | Detalhes 


 a| 
Velocidade
 a| 
A operação clone do SnapManager usa o recurso FlexClone disponível com o Data ONTAP. Isso permite clonar rapidamente grandes volumes de dados.



 a| 
Eficiência de espaço
 a| 
Quando você cria um clone usando o SnapManager, o espaço é necessário apenas para as alterações entre o backup e o clone. Um clone do SnapManager é uma cópia Snapshot gravável do banco de dados original e pode ser expandido conforme a necessidade. Em contraste, um clone físico do banco de dados requer que você tenha espaço suficiente disponível para copiar todo o banco de dados.



 a| 
Cópia virtual
 a| 
Você pode usar o banco de dados clonado como se fosse o banco de dados original. Por exemplo, você pode usar um clone para verificações de teste, plataforma e atualização, várias simulações em um grande conjunto de dados e testes e testes de escritório remoto. As alterações ao clone não afetam o banco de dados original. Depois que o banco de dados é clonado, o banco de dados clonado está totalmente operacional.



 a| 
Simplicidade
 a| 
Você pode clonar um banco de dados para qualquer host usando comandos SnapManager.

|===
Você pode clonar um backup no storage primário (local) ou em um backup protegido no storage secundário (remoto). No entanto, você não pode clonar um backup se a operação de backup estiver em andamento ou se o backup tiver sido transferido para o storage secundário.

Você deve garantir que os seguintes pré-requisitos sejam atendidos antes que um banco de dados possa ser clonado:

* Certifique-se de que o diretório [/etc|/var/opt/Oracle]/oratab não contenha uma entrada apontando para o identificador do sistema de destino.
* Exclua o arquivo spfile<SID>.ora do ORACLE_Home/dbs.
* Exclua o arquivo init<SID>.ora do ORACLE_Home/dbs.
* Exclua destinos de despejo Oracle especificados no arquivo de especificação do clone.
* Exclua os arquivos de controle Oracle especificados no arquivo de especificação clone.
* Exclua os arquivos de log redo Oracle especificados no arquivo de especificação do clone.


Você deve fornecer ao clone um novo identificador de sistema. Não é possível executar simultaneamente dois bancos de dados com o mesmo identificador de sistema no mesmo host. Você pode ter um clone em um host diferente usando o mesmo identificador de sistema. Você pode dar ao clone um rótulo ou permitir que o SnapManager crie um rótulo usando o identificador do sistema, a data e a hora em que o clone foi criado.

Ao inserir um rótulo, você não deve incluir espaços ou carateres especiais.

Como parte do processo de clonagem, o SnapManager cria os arquivos e os parâmetros necessários do Oracle para o banco de dados clonado. Um exemplo de um arquivo Oracle necessário é init<SID>.ora.

Quando você clonar um banco de dados, o SnapManager cria um novo arquivo init<SID>.ora para o banco de dados no diretório ORACLE_Home/dbs.

Quando o SnapManager clona o armazenamento de um banco de dados, ele também cria um novo ponto de montagem do sistema de arquivos, mas não altera a estrutura do diretório sob o ponto de montagem da CLI do SnapManager. No entanto, a partir da GUI do SnapManager, você pode alterar a estrutura de diretórios e os metadados do sistema de arquivos.

O Oracle 11g em um ambiente Direct NFS (DNFS) permite uma configuração de ponto de montagem adicional, como vários caminhos para balanceamento de carga no arquivo oranfstab. O SnapManager não modifica esse arquivo, portanto, quaisquer propriedades adicionais que você deseja usar devem ser adicionadas manualmente ao arquivo oranfstab após a clonagem com o SnapManager.

Você pode clonar um banco de dados do Real Application Cluster (RAC), bem como um banco de dados não agrupado. Um clone do RAC começa como um único banco de dados.

Você pode clonar um backup de banco de dados para o host no qual o banco de dados reside ou para um host alternativo.

Você também pode clonar um banco de dados ASM para um host remoto. Ao fazer isso, você deve garantir que a instância ASM esteja sendo executada no host remoto.

Se o banco de dados clonado estava usando um spfile, o SnapManager cria um spfile para o clone. Ele coloca esse arquivo no diretório ORACLE_Home/dbs e cria a estrutura de diretório para os arquivos de diagnóstico. O nome do arquivo é spfile <SID>.ora.
