---
permalink: unix-administration/concept_general_layout_and_configuration.html 
sidebar: sidebar 
keywords: recommend, general, database, layout, storage, configuration, avoid, issue, disk, group, file, lun 
summary: Conhecer os layouts gerais de banco de dados recomendados e as configurações de armazenamento pode ajudá-lo a evitar problemas relacionados a grupos de discos, tipos de arquivos e espaços de tabela. 
---
= Layouts gerais de banco de dados recomendados e configurações de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conhecer os layouts gerais de banco de dados recomendados e as configurações de armazenamento pode ajudá-lo a evitar problemas relacionados a grupos de discos, tipos de arquivos e espaços de tabela.

* Não inclua arquivos de mais de um tipo de sistema de arquivos SAN ou gerenciador de volumes em seu banco de dados.
+
Todos os arquivos que compõem um banco de dados devem residir no mesmo tipo de sistema de arquivos.

* O SnapManager requer vários tamanhos de bloco de 4K KB.
* Inclua o identificador do sistema de banco de dados no arquivo oratab.
+
Inclua uma entrada no arquivo oratab para cada banco de dados a ser gerenciado. O SnapManager depende do arquivo oratab para determinar qual casa do Oracle usar.

* Se você deseja Registrar backups do SnapManager com o Oracle Recovery Manager (RMAN), você deve criar perfis habilitados para RMAN.


Se você quiser aproveitar a nova restauração baseada em volume ou a restauração completa do grupo de discos, considere as seguintes diretrizes relacionadas aos sistemas de arquivos e grupos de discos:

* Vários bancos de dados não podem compartilhar o mesmo grupo de discos de Gerenciamento Automático de armazenamento (ASM).
* Um grupo de discos contendo arquivos de dados não pode conter outros tipos de arquivos.
* O número de unidade lógica (LUN) para o grupo de discos de arquivo de dados deve ser o único objeto no volume de armazenamento.


A seguir estão algumas diretrizes para separação de volumes:

* Os arquivos de dados para apenas um banco de dados devem estar no volume.
* Você deve usar volumes separados para cada uma das seguintes classificações de arquivos: Binários de banco de dados, arquivos de dados, arquivos de log refazer on-line, arquivos de log refazer arquivados e arquivos de controle.
* Você não precisa criar um volume separado para arquivos temporários de banco de dados porque o SnapManager não faz backup de arquivos temporários de banco de dados.

