---
permalink: unix-administration/concept_variables_available_in_custom_script_for_restore_operation.html 
sidebar: sidebar 
keywords: snapmanager, context, information, environment, variable, restore, operation 
summary: O SnapManager fornece informações de contexto na forma de variáveis de ambiente relacionadas à operação de restauração que está sendo executada. Por exemplo, seu script pode recuperar o nome do host original e o rótulo do backup que é restaurado. 
---
= Variáveis disponíveis nos scripts de tarefa para a operação de restauração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager fornece informações de contexto na forma de variáveis de ambiente relacionadas à operação de restauração que está sendo executada. Por exemplo, seu script pode recuperar o nome do host original e o rótulo do backup que é restaurado.

A tabela a seguir lista as variáveis de ambiente que você pode usar em seus scripts:

|===
| Variáveis | Descrição | Formato 


 a| 
SM_OPERATION_ID
 a| 
Especifica o ID da operação atual
 a| 
cadeia de carateres



 a| 
SM_PROFILE_NAME
 a| 
Especifica o nome do perfil usado
 a| 
cadeia de carateres



 a| 
SM_HOST
 a| 
Especifica o nome do host do banco de dados
 a| 
cadeia de carateres



 a| 
SM_OS_USER
 a| 
Especifica o proprietário do sistema operacional (SO) do banco de dados
 a| 
cadeia de carateres



 a| 
SM_OS_GROUP
 a| 
Especifica o grupo de SO do banco de dados
 a| 
cadeia de carateres



 a| 
SM_BACKUP_TYPE
 a| 
Especifica o tipo de backup (on-line, off-line ou automático)
 a| 
cadeia de carateres



 a| 
SM_BACKUP_LABEL
 a| 
Especifica a etiqueta de backup
 a| 
cadeia de carateres



 a| 
SM_BACKUP_ID
 a| 
Especifica o ID de backup
 a| 
cadeia de carateres



 a| 
SM_BACKUP_PROFILE
 a| 
Especifica o perfil usado para o backup
 a| 
cadeia de carateres



 a| 
SM_RECOVERY_TYPE
 a| 
Especifica as informações de configuração de recuperação
 a| 
cadeia de carateres



 a| 
SM_VOLUME_RESTORE_MODE
 a| 
Especifica a configuração de restauração de volume
 a| 
cadeia de carateres



 a| 
SM_TARGET_ARQUIVADOR_NAME
 a| 
Especifica o nome do sistema de armazenamento de destino *Nota:* se mais de um sistema de armazenamento for usado, os nomes do sistema de armazenamento devem ser separados por vírgulas.
 a| 
cadeia de carateres



 a| 
SM_TARGET_VOLUME_NAME
 a| 
Especifica o nome do volume de destino *Nota:* o nome do volume de destino deve ser prefixado com o nome do dispositivo de armazenamento, por exemplo, SM_TARGET_ARQUIVADOR_name/SM_TARGET_VOLUME_NAME.
 a| 
cadeia de carateres



 a| 
SM_HOST_FILE_SYSTEM
 a| 
Especifica o sistema de arquivos host
 a| 
cadeia de carateres



 a| 
SM_SNAPSHOT_NAMES
 a| 
Especifica a lista de instantâneos *Observação:* o nome das cópias Snapshot deve ser prefixado com o nome do sistema de armazenamento e o nome do volume. Os nomes das cópias Snapshot são separados por vírgulas.
 a| 
array de cadeia de carateres



 a| 
SM_ASM_DISK_GROUPS
 a| 
Especifica a lista do grupo de discos ASM
 a| 
array de cadeia de carateres



 a| 
SM_ARCHIVE_LOGS_DIRECTORY
 a| 
Especifica o diretório de logs de arquivo *Nota:* se os logs de arquivo estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.
 a| 
array de cadeia de carateres



 a| 
SM_REDO_LOGS_DIRECTORY
 a| 
Especifica o diretório refazer logs *Observação:* se os logs de refazer estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.
 a| 
array de cadeia de carateres



 a| 
SM_CONTROL_FILES_DIRECTORY
 a| 
Especifica o diretório de arquivos de controle *Nota:* se os arquivos de controle estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.
 a| 
array de cadeia de carateres



 a| 
SM_DATA_FILES_DIRECTORY
 a| 
Especifica o diretório de arquivos de dados *Nota:* se os arquivos de dados estiverem localizados em mais de um diretório, os nomes desses diretórios serão separados por vírgulas.
 a| 
array de cadeia de carateres

|===