---
permalink: unix-administration/reference_troubleshooting_storage_system_renaming_issue.html 
sidebar: sidebar 
keywords: face, issue, renaming, storage, system, succesful, rename, storage, system, troubleshoot 
summary: Você pode enfrentar problemas ao renomear um sistema de armazenamento ou depois de ter renomeado o sistema de armazenamento com êxito. 
---
= Solução de problemas de renomeação do sistema de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode enfrentar problemas ao renomear um sistema de armazenamento ou depois de ter renomeado o sistema de armazenamento com êxito.

Quando você tenta renomear o sistema de armazenamento, a operação pode falhar com a seguinte mensagem de erro: SMO-05085 nenhum controlador de armazenamento "FAS3020-rtp07New" está associado ao perfil

Você deve inserir o endereço IP ou o nome do sistema de armazenamento listado quando você executar o comando smo storage list.

Depois de renomear o sistema de storage, as operações do SnapManager podem falhar se o SnapManager não reconhecer o sistema de storage. Você deve executar algumas etapas adicionais no host do servidor do Gerenciador DataFabric e no host do servidor SnapManager para resolver esse problema.

Execute as seguintes etapas no host do servidor DataFabric Manager:

. Exclua o endereço IP e o host do sistema de armazenamento anterior no arquivo do host localizado em /etc/hosts no host do servidor DataFabric Manager.
. Adicione o novo endereço IP e o host do novo sistema de armazenamento no arquivo host localizado em /etc/hosts no host do servidor DataFabric Manager.
. Altere o nome do host de armazenamento digitando o seguinte comando: dfm host rename -a old_host_namenew_host_name
. Defina o novo endereço IP no host inserindo o seguinte comando: dfm host set old_host_name_or_objID hostPrimaryAddress: New_storage_controller_ip_address
+

NOTE: Só tem de executar esta etapa se tiver especificado o endereço IP como o novo nome do sistema de armazenamento.

. Atualize o novo nome do sistema de armazenamento no host do servidor DataFabric Manager inserindo o seguinte comando: dfm host diag old_storage_name
+
Você pode verificar se o nome do controlador de armazenamento anterior é substituído pelo novo nome do controlador de armazenamento digitando o seguinte comando: dfm host Discover new_storage_name



Execute as etapas a seguir como um usuário raiz no host do servidor SnapManager.


NOTE: Ao inserir o novo nome do controlador de armazenamento, certifique-se de usar o nome de alias do sistema e não o nome de domínio totalmente qualificado (FQDN).

. Exclua o nome do sistema de armazenamento anterior digitando o seguinte comando: SnapDrive config delete old_storage_name
+

NOTE: Se você não excluir o nome do sistema de armazenamento anterior, todas as operações do SnapManager falharão.

. Exclua o endereço IP e o host do sistema de armazenamento anterior no arquivo do host localizado em etc/hosts no host do banco de dados de destino.
. Adicione o novo endereço IP e o host do novo sistema de armazenamento no arquivo do host localizado em /etc/hosts no host do banco de dados de destino.
. Adicione o novo nome do sistema de armazenamento inserindo o seguinte comando: SnapDrive config set root new_storage_name
. Mapeie os nomes do sistema de armazenamento anterior e posterior inserindo o seguinte comando: SnapDrive config migrate set old_storage_namenew_storage_name
. Exclua o caminho de gerenciamento do sistema de armazenamento anterior digitando o seguinte comando:SnapDrive config delete -mgmtpath old_storage_name
. Adicione o caminho de gerenciamento para o novo sistema de armazenamento inserindo o seguinte comando: SnapDrive config set -mgmtpath new_storage_name
. Atualize o conjunto de dados para arquivos de dados e arquivos de log de arquivo com o novo nome do sistema de armazenamento inserindo o seguinte comando: SnapDrive dataset changehostname -dndataset_name-oldnameold_storage_name-newnamenew_storage_name
. Atualize o perfil para o novo nome do sistema de armazenamento inserindo o seguinte comando: smo storage rename -profileprofile_name-oldnameold_storage_name-newnamenew_storage_name
. Verifique o sistema de armazenamento associado ao perfil inserindo o seguinte comando: smo storage list -profileprofile_name

