---
permalink: unix-administration/reference_the_smosmsapbackup_verify_command.html 
sidebar: sidebar 
keywords: run, backup, verify, command, format, oracle, valid, smo 
summary: Você pode executar o comando de verificação de backup para ver se o backup está em um formato válido para o Oracle. 
---
= O comando smo backup check
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o comando de verificação de backup para ver se o backup está em um formato válido para o Oracle.



== Sintaxe

[listing]
----

        smo backup verify
-profile profile_name
[-label backup_name \| \[-id guid\]
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\}\]
\[-force\]
\[-dump\]
\[-quiet \| -verbose\]
----


== Parâmetros

* *-profile profile_name*
+
Especifica o perfil para o qual você deseja verificar um backup. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *-id guid*
+
Verifica a cópia de segurança com o GUID especificado. O GUID é gerado pelo SnapManager quando cria uma cópia de segurança. Você pode usar o comando smo backup list para exibir o GUID para cada backup.

* *-label label_name*
+
Verifica a cópia de segurança com a etiqueta especificada.

* *-dump*
+
Coleta os arquivos de despejo após a operação de verificação de backup bem-sucedida ou com falha.

* *-força*
+
Força o banco de dados no estado necessário para executar a operação de verificação.

* *-silencioso*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo

O seguinte é um exemplo de verificação do backup:

[listing]
----
smo backup verify -profile SALES1 -label full_backup_sales_May -quiet
----
[listing]
----
DBVERIFY - Verification starting : FILE = +SMO_1_1161675083835/smo/datafile/data.277.582482539 ...
----
*Informações relacionadas*

xref:task_verifying_database_backups.adoc[Verificando backups de bancos de dados]
