---
permalink: unix-administration/reference_the_smosmsapcredential_set_command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, secure, resource, host, repositories, database, profile, specified, argument, smo 
summary: Esse comando permite definir as credenciais para que os usuários acessem recursos seguros, como hosts, repositórios e perfis de banco de dados. A senha do host é a senha do usuário no host no qual o SnapManager está sendo executado. A senha do repositório é a senha do usuário Oracle que contém o esquema do repositório SnapManager. A senha do perfil é uma senha que é composta pela pessoa que cria o perfil. Para as opções de host e repositório, se a opção opcional -password não estiver incluída, você será solicitado a digitar uma senha do tipo especificado nos argumentos de comando. 
---
= O comando smo Credential set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esse comando permite definir as credenciais para que os usuários acessem recursos seguros, como hosts, repositórios e perfis de banco de dados. A senha do host é a senha do usuário no host no qual o SnapManager está sendo executado. A senha do repositório é a senha do usuário Oracle que contém o esquema do repositório SnapManager. A senha do perfil é uma senha que é composta pela pessoa que cria o perfil. Para as opções de host e repositório, se a opção opcional -password não estiver incluída, você será solicitado a digitar uma senha do tipo especificado nos argumentos de comando.



== Sintaxe

[listing]
----

        smo credential set
\[-host
-name host_name
-username username\]
\[-password password\] \] \|
\[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username\] \[-password repo_password\] \]
-port repo_port \|
\[-profile
-name profile_name\]
\[-password password\] \]
\[-quiet \| -verbose\]
----


== Parâmetros

* *-host hostname*
+
Especifica o nome ou endereço IP do servidor host no qual o SnapManager está sendo executado.

+
O parâmetro -host inclui as seguintes opções:

+
** -Name host_name: Especifica o nome do host para o qual você definirá a senha.
** -Username user_name: Especifica o nome de usuário no host.
** -Password password: Especifica a senha do usuário no host.


* *-repositório -dbname*
+
Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.

+
O parâmetro -repositório inclui as seguintes opções:

+
** -Dbnamepo_Service_name: Especifica o nome do banco de dados que armazena o perfil. Use o nome global ou o SID.
** -Host repo_host: Especifica o nome ou endereço IP do servidor host no qual o banco de dados do repositório é executado.
** -Login-username repo_username: Especifica o nome de usuário necessário para acessar o banco de dados que armazena o repositório.
** -Password password: Especifica a senha necessária para acessar o banco de dados que armazena o repositório.
** -Port repo_port: Especifica o número da porta TCP usado para acessar o banco de dados que armazena o repositório.


* *-profile -name profile_name*
+
Especifica o perfil ao qual o banco de dados está associado.

+
O parâmetro -profile inclui a seguinte opção:

+
** -Nome profilename: Especifica o nome do perfil para o qual você definirá a senha.
** -Password: Especifica a senha necessária para acessar o perfil.


* *-silencioso*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.





== Exemplo de comando para definir credenciais de repositório

O exemplo a seguir define credenciais para um repositório.

[listing]
----

smo credential set -repository -dbname SMOREPO -host hotspur -port 1521 -login -username chris
Password for chris@hotspur:1521/SMOREPO : ********
Confirm password for chris@hotspur:1521/SMOREPO : ********
----
[listing]
----
SMO-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMO-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Exemplo de comando para definir credenciais de host

Como uma credencial de host representa uma credencial real do sistema operacional, ela deve incluir o nome de usuário além da senha.

[listing]
----
smo credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
*Informações relacionadas*

xref:concept_snapmanager_security.adoc[Como o SnapManager mantém a segurança]
