---
permalink: unix-administration/reference_supported_partition_devices.html 
sidebar: sidebar 
keywords: partition, snapmanager, support, device, red, hat, enterprise, linux, 5x, oracle 
summary: Você deve conhecer os diferentes dispositivos de partição que são suportados no SnapManager. 
---
= Dispositivos de partição suportados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve conhecer os diferentes dispositivos de partição que são suportados no SnapManager.

A tabela a seguir fornece informações sobre partições e como elas podem ser ativadas para diferentes sistemas operacionais:

|===
| Sistema operacional | Partição única | Partição múltipla | Dispositivos que não são partições | Sistema de ficheiros ou dispositivos RAW 


 a| 
Red Hat Enterprise Linux 5x ou

Oracle Enterprise Linux 5x
 a| 
Sim
 a| 
Não
 a| 
Não
 a| 
ext3*



 a| 
Red Hat Enterprise Linux 6xor

Oracle Enterprise Linux 6x
 a| 
Sim
 a| 
Não
 a| 
Não
 a| 
ext3 ou ext4*



 a| 
SUSE Linux Enterprise Server 11
 a| 
Sim
 a| 
Não
 a| 
Não
 a| 
ext3*



 a| 
SUSE Linux Enterprise Server 10
 a| 
Não
 a| 
Não
 a| 
Sim
 a| 
ext3***



 a| 
Red Hat Enterprise Linux 5x ou lateror

Oracle Enterprise Linux 5x ou posterior
 a| 
Sim
 a| 
Não
 a| 
Sim
 a| 
ASM com ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4or

SUSE Linux Enterprise Server 11
 a| 
Sim
 a| 
Não
 a| 
Sim
 a| 
ASM com ASMlib**



 a| 
SUSE Linux Enterprise Server 10 SP4 ou mais recente

SUSE Linux Enterprise Server 11
 a| 
Sim
 a| 
Não
 a| 
Não
 a| 
ASM sem ASMlib***

|===
Para obter mais informações sobre as versões suportadas do sistema operativo, consulte a Matriz de interoperabilidade.
