---
permalink: unix-administration/reference_the_smosmsapbackup_update_command.html 
sidebar: sidebar 
keywords: run, backup, update, command, retention, policy, smo 
summary: Você pode executar o comando de atualização de backup para atualizar a política de retenção de backup. 
---
= O comando smo backup update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o comando de atualização de backup para atualizar a política de retenção de backup.



== Sintaxe

[listing]
----

        smo backup update
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id guid\]
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\}\]
\[-comment comment_text\]
[-quiet | -verbose]
----


== Parâmetros

* *-profile profile_name*
+
Especifica o perfil para o qual atualizar backups. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *-id guid*
+
Verifica a cópia de segurança com o GUID especificado. O GUID é gerado pelo SnapManager quando cria uma cópia de segurança. Você pode usar o comando smo backup list para exibir o GUID para cada backup.

* * etiqueta de etiqueta*
+
Especifica o rótulo de backup e o escopo do backup como arquivo de dados ou log de arquivamento.

* *-data*
+
Especifica os arquivos de dados.

* *-archivelogs*
+
Especifica os arquivos de log de arquivamento.

* *-comentário comment_text*
+
Introduza texto (até 200 carateres) sobre a atualização de cópia de segurança. Você pode incluir espaços.

* *-silencioso*
+
Exibe apenas mensagens de erro no console. O padrão é exibir mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.

* *-retenha (por hora) | -diariamente | -semanal | -mensal | -ilimitado*
+
Especifica se o backup deve ser retido por hora, dia, semanal, mensal ou ilimitado. Se -retent não for especificado, a classe de retenção padrão é -Hourly. Para manter backups para sempre, use a opção -Unlimited. A opção -Unlimited torna o backup inelegível para exclusão.





== Exemplo

O exemplo a seguir atualiza o backup para definir a política de retenção como ilimitada:

[listing]
----
smo backup update -profile SALES1 -label full_backup_sales_May
-retain -unlimited -comment save_forever_monthly_backup
----
*Informações relacionadas*

xref:task_changing_the_backup_retention_policy.adoc[Alterar a política de retenção de backup]

xref:task_retaining_backups_forever.adoc[Mantendo backups para sempre]

xref:task_freeing_or_deleting_retention_policy_exempt_backups.adoc[Liberar ou excluir backups isentos de política de retenção]
