---
permalink: unix-administration/reference_the_smosmsapbackup_mount_command.html 
sidebar: sidebar 
keywords: run, backup, mount, command, perform, recover, operation, external, tool, smo 
summary: Você pode executar o comando backup mount para montar um backup para executar uma operação de recuperação usando uma ferramenta externa. 
---
= O comando smo backup mount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar o comando backup mount para montar um backup para executar uma operação de recuperação usando uma ferramenta externa.



== Sintaxe

[listing]
----

        smo backup mount
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
[-host  host]
\[-from-secondary \{-copy-id id\}\]
\[-dump\]
[-quiet | -verbose]
----


== Parâmetros

* *-profile profile_name*
+
Especifica o perfil associado ao backup que você deseja montar. O perfil contém o identificador da base de dados e outras informações da base de dados.

* *-id guid*
+
Monta a cópia de segurança com o GUID especificado. O GUID é gerado pelo SnapManager quando cria uma cópia de segurança. Você pode usar o comando smo backup list para exibir o GUID para cada backup.

* * etiqueta de etiqueta*
+
Monta o backup com a etiqueta especificada.

* *-data*
+
Especifica os arquivos de dados.

* *-archivelogs*
+
Especifica os arquivos de log de arquivamento.

* *-from-secundary -copy-id id id*
+
Monta o backup do armazenamento secundário. Se essa opção não for especificada, o SnapManager monta o backup do armazenamento primário. Você pode usar essa opção se o backup for liberado.

+
Você deve especificar a opção -copy-id sempre que especificar a opção -from-secundary. Se houver mais de um backup no sistema de armazenamento secundário, a opção -copy-id é usada para especificar qual cópia de backup no armazenamento secundário deve ser usada para montar o backup.

+

NOTE: Se você estiver usando o Data ONTAP operando no modo 7, você deve especificar um valor válido para a opção -copy-id. No entanto, se você estiver usando o Clustered Data ONTAP, a opção -copy-id não é necessária.

* *-host host *
+
Especifica o host no qual você deseja montar o backup.

* *-dump*
+
Coleta os arquivos de despejo após a operação de montagem bem-sucedida ou com falha.

* *-silencioso*
+
Exibe apenas mensagens de erro no console. A predefinição é apresentar mensagens de erro e aviso.

* *-verbose*
+
Exibe mensagens de erro, aviso e informativas no console.




NOTE: Você deve usar esse comando somente se estiver usando uma ferramenta externa, como o Oracle Recovery Manager (RMAN). O SnapManager manipula automaticamente a montagem de backups se você usar o comando smo backup restore para restaurar o backup. Este comando exibe uma lista, que mostra os caminhos onde as cópias Snapshot foram montadas. Esta lista é exibida somente quando a opção -verbose é especificada.



== Exemplo

O exemplo a seguir monta o backup:

[listing]
----
smo backup mount -profile SALES1 -label full_backup_sales_May -verbose
SMO-13046 [INFO ]: Operation GUID 8abc013111b9088e0111b908a7560001 starting on Profile SALES1
SMO-08052 [INFO ]: Beginning to connect mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/logs from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_logs.
SMO-08025 [INFO ]: Beginning to connect mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08027 [INFO ]: Finished connecting mount /mnt/ssys1/data from snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001_0 of volume hs_data.
SMO-08053 [INFO ]: Finished connecting mount(s) [/mnt/ssys1/logs, /mnt/ssys1/data] from logical snapshot SMO_SALES1_hsdb1_F_C_1_8abc013111a450480111a45066210001.
SMO-13037 [INFO ]: Successfully completed operation: Backup Mount
SMO-13048 [INFO ]: Operation Status: SUCCESS
SMO-13049 [INFO ]: Elapsed Time: 0:01:00.981
Operation Id [8abc013111b9088e0111b908a7560001] succeeded.
----
*Informações relacionadas*

xref:task_mounting_backups.adoc[Montagem de backups]
