---
permalink: unix-administration/task_updating_target_database_hostname_associated_with_a_profile.html 
sidebar: sidebar 
keywords: snapmanager, 3.2, oracle, provide, ability, update, host, name, target, database, snapmanager, profile, smo 
summary: 'O SnapManager (3,2 ou posterior) para Oracle fornece a capacidade de atualizar o nome do host do banco de dados de destino no perfil do SnapManager.' 
---
= Atualizando o nome do host do banco de dados de destino associado a um perfil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager (3,2 ou posterior) para Oracle oferece a capacidade de atualizar o nome do host do banco de dados de destino no perfil do SnapManager.

* O diretório home do usuário local deve estar ciente dos mapeamentos de perfil para repositório.
* As sessões da interface gráfica do usuário (GUI) do SnapManager devem ser fechadas.
* Em um ambiente de Real Application clusters (RAC), os clones ou backups montados disponíveis no host especificado no perfil devem ser excluídos e desmontados.


Você pode atualizar o perfil com o novo nome de host usando apenas a CLI.

*Cenários não suportados para alterar o nome do host do banco de dados de destino no perfil*

Os cenários a seguir não são suportados para alterar o nome do host do banco de dados de destino no perfil:

* Alterar o nome do host do banco de dados de destino usando a GUI do SnapManager
* Reverter o banco de dados do repositório depois de atualizar o nome do host do banco de dados de destino do perfil
* Atualizando vários perfis para um novo nome de host de banco de dados de destino executando um único comando
* Alterar o nome do host do banco de dados de destino quando qualquer operação do SnapManager estiver em execução
* Alterar o nome do host do banco de dados de destino se o SnapManager estiver instalado no Solaris e se os LUNs (números de unidade lógica) do banco de dados forem criados usando o sistema de arquivos montado no host com pilha SVM.



NOTE: Depois de atualizar o nome do host do banco de dados de destino no perfil, somente o nome do host do banco de dados de destino será alterado. Todos os outros parâmetros de configuração definidos no perfil são retidos.

Depois de atualizar o novo nome de host do banco de dados de destino em um perfil habilitado para proteção, o mesmo conjunto de dados e políticas de proteção são mantidas para o perfil atualizado.

Depois de alterar o nome do host de destino, você deve garantir que você atualize o nome do host para todos os perfis protegidos existentes antes de criar os novos perfis protegidos. Para atualizar o nome do host para um perfil, execute o comando smo profile update.

Depois de atualizar o nome do host do banco de dados de destino, não é possível excluir ou dividir o clone ou desmontar o backup se o clone ou o backup montado não estiver disponível no novo host. Em tais cenários, executar as operações do SnapManager do novo host leva à falha, bem como entradas obsoletas no host anterior. Para executar operações do SnapManager, você deve reverter para o nome de host anterior usando a atualização de perfil.

. Introduza o seguinte comando:
`smo profile update -profileprofile [-profile-passwordprofile_password][-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port]] [{-rman{-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname}}} | -remove-rman]-osaccountosaccount-osgrouposgroup [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][[-protect [-protection-policypolicy_name]]| [[-noprotect]] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]] [-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-protection-policypolicy_name] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
Outras opções para este comando são as seguintes:

+
[-force] [-noprompt]

+
|===


| Se você quiser... | Então... 


 a| 
*Altere o nome do host do banco de dados de destino*
 a| 
Especifique -hostnew_dB_host

|===
. Para exibir o nome do host do banco de dados de destino do perfil, digite o seguinte comando:
`smo profile show`

