---
permalink: unix-administration/task_using_protection_manager_to_provision_the_new_dataset.html 
sidebar: sidebar 
keywords: smo_paydb, dataset, create, storage, administrator, protection, manager, assign, provision, node, netapp 
summary: Depois que o conjunto de dados smo_paydb é criado, o administrador de armazenamento usa o Protection Manager para atribuir recursos do sistema de armazenamento para provisionar o nó Backup do conjunto de dados. 
---
= Uso do Protection Manager para provisionar o novo conjunto de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois que o conjunto de dados smo_paydb é criado, o administrador de armazenamento usa o Protection Manager para atribuir recursos do sistema de armazenamento para provisionar o nó Backup do conjunto de dados.

Antes de provisionar o conjunto de dados recém-criado, o administrador de armazenamento confere ao parceiro DBA o nome do conjunto de dados especificado no perfil.

Neste caso, o nome do conjunto de dados é smo_payroll.tech.com_PAYDB.

. Vá para o console de gerenciamento do NetApp do Gerenciador de proteção.
. Na barra de menus, clique em *Data* > *Datasets* > *Overview*.
+
A guia Datasets (conjuntos de dados) da janela Datasets (conjuntos de dados) exibe uma lista de conjuntos de dados que inclui o conjunto de dados que acabou de ser criado através do SnapManager.

. Localize e selecione o conjunto de dados *smo_payroll.tech.com_PAYDB*.
+
Quando você seleciona este conjunto de dados, a área de gráfico exibe o conjunto de dados smo_paydb com seu nó de backup não provisionado. Seu status de conformidade é sinalizado como não-conformante.

. Com o conjunto de dados smo_paydb ainda realçado, clique em *Edit*.
+
O console de gerenciamento NetApp do Gerenciador de proteção exibe a janela Editar conjunto de dados para o conjunto de dados *smo_payroll.tech.com_PAYDB*. O painel de navegação da janela exibe opções de configuração para o nó principal do conjunto de dados, a conexão de backup e o nó de backup.

. No painel de navegação, localize as opções para o nó de backup do conjunto de dados e selecione *Provisioning/pools de recursos*.
+
A janela Editar conjunto de dados exibe uma configuração para a política de provisionamento padrão e uma lista de pools de recursos disponíveis.

. Para este exemplo, selecione o pool de recursos *paydb_backup_resource* e clique em *>*.
+
O pool de recursos selecionado é listado no campo "pools de recursos para este nó".

. Clique em *Finish* para salvar suas alterações.


O Protection Manager provisiona automaticamente o nó de backup secundário com recursos do pool de recursos paydb_backup_resource.
