---
permalink: unix-administration/task_configuring_mail_server_for_a_repository.html 
sidebar: sidebar 
keywords: snapmanager, enable, specify, mail, server, detail, alert, repository, ip, address, email, server, smo, notification, set 
summary: O SnapManager permite que você especifique os detalhes do servidor de e-mail a partir dos quais os alertas de e-mail são enviados. 
---
= Configurando um servidor de e-mail para um repositório
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapManager permite que você especifique os detalhes do servidor de e-mail a partir dos quais os alertas de e-mail são enviados.

O SnapManager permite especificar o nome do host ou endereço IP do servidor de e-mail do remetente e o número da porta do servidor de e-mail para um nome de banco de dados do repositório que requer notificação por e-mail. Você pode configurar o número da porta do servidor de e-mail em um intervalo de 0 a 65535; o valor padrão é 25. Se necessitar de autenticação para o endereço de correio eletrónico, pode especificar o nome de utilizador e a palavra-passe.

Você deve especificar o nome ou o endereço IP do servidor host que manipula a notificação de e-mail.

. Para configurar o servidor de e-mail para enviar alertas de e-mail, digite o seguinte comando: smo notification set -sender-emailemail_address-mailhost-mailportmailport [-Authentication-usernameusername-passwordpassword] -repositório-portrepo_port-dbnamepo_Service_name-hostrepo_host-login-usernamepo_usernamepo_usernamepo_username
+
Outras opções para este comando são as seguintes:

+
[-force] (força)

+
|===
| Para fazer o seguinte... | Então... 


 a| 
*Para especificar o endereço de e-mail do remetente.*
 a| 
Especifique a opção -sender-email. No SnapManager 3,2 para Oracle, você pode incluir hífen (-) ao especificar o nome de domínio do endereço de e-mail. Por exemplo, você pode especificar o endereço de e-mail do remetente como -sender-emailuser@org-corp.com.



 a| 
*Para especificar o nome do host ou endereço IP do servidor de e-mail do remetente.*
 a| 
Especifique a opção -mailhost.



 a| 
*Para especificar o número da porta do servidor de e-mail para um nome de banco de dados do repositório que requer notificação por e-mail. Você pode configurar o número da porta do servidor de e-mail em um intervalo de zero a 65535; o valor padrão é 25.*
 a| 
Especifique a opção -mailport.



 a| 
*Especifique o nome de usuário e a senha se você precisar de autenticação para o endereço de e-mail.*
 a| 
Especifique a opção -Authentication seguida do nome de usuário e senha.

|===


O exemplo a seguir configura o servidor de e-mail.

[listing]
----
smo notification set -sender-email admin1@org.com -mailhost hostname.org.com -mailport 25 authentication -username admin1 -password admin1 -repository -port 1521 -dbname SMOREPO -host hotspur -login -username grabal21 -verbose
----