---
permalink: unix-administration/task_cloning_a_database_to_an_alternate_host.html 
sidebar: sidebar 
keywords: clone, create, command, database, backup, alternate, host, cloning, exist 
summary: Você pode usar o comando clone create para clonar um backup de banco de dados em um host alternativo. 
---
= Clonar um banco de dados para um host alternativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o comando clone create para clonar um backup de banco de dados em um host alternativo.

* Crie um perfil ou tenha um perfil existente.
* Crie um backup completo ou tenha um backup de banco de dados existente.
* Crie uma especificação de clone ou tenha uma especificação de clone existente.
+
.. Para clonar um banco de dados para um host alternativo, digite o seguinte comando: smo clone create -backup-label backup_label_name-newsid new_sid-host target_host-label clone_label-commentcomment_text-profileprofile_name-clonespec full_path_to_clonespec
+
O Oracle não permite que você execute dois bancos de dados com o mesmo SID simultaneamente no mesmo host. Por causa disso, você deve fornecer um novo SID para cada clone. No entanto, você pode ter um banco de dados em outro host com o mesmo SID.





*Informações relacionadas*

xref:task_creating_profiles.adoc[Criando perfis]

xref:task_cloning_databases_from_backups.adoc[Clonar bancos de dados de backups]

xref:task_creating_clone_specifications.adoc[Criando especificações de clone]

xref:reference_the_smosmsapclone_create_command.adoc[O comando smo clone create]
