---
permalink: unix-administration/task_changing_the_retention_policy_default_behavior.html 
sidebar: sidebar 
keywords: backup, expire, based, retention, policy, snapmanager, determine, delete, backup, setting, policy, default, behavior 
summary: Quando um backup expira com base na política de retenção, o SnapManager determina se deseja excluir o backup com base nas configurações de retenção. A exclusão de backups é o comportamento padrão. Você pode alterar esse comportamento padrão e optar por liberar os backups desprotegidos. 
---
= Alterar o comportamento padrão da política de retenção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um backup expira com base na política de retenção, o SnapManager determina se deseja excluir o backup com base nas configurações de retenção. A exclusão de backups é o comportamento padrão. Você pode alterar esse comportamento padrão e optar por liberar os backups desprotegidos.

Por padrão, o SnapManager exclui ou libera backups, dependendo se eles estão protegidos ou não da seguinte forma:

* Para backups protegidos, o SnapManager libera os backups locais quando expiram.
* Para backups não protegidos, o SnapManager exclui os backups locais quando expiram.
+
Você pode alterar esse comportamento padrão.



Para backups protegidos, o SnapManager não considera o seguinte para determinar se deseja excluir a cópia local:

* O backup para o storage secundário falhou ou está em processo de proteção.
+
Isso permite a transferência de backups para o storage secundário antes que a política de retenção seja aplicada.

* A cópia foi posteriormente eliminada do armazenamento secundário.
+
.. Acesse o seguinte local padrão:
+
local de instalação padrão do smo/properties/smo.config

.. Edite o arquivo smo.config.
.. Defina a propriedade ret.alwaysFreeExpiredBackups no arquivo smo.config como true.
+
Por exemplo, ret.alwaysFreeExpiredBackups: True





*Informações relacionadas*

xref:reference_the_smosmsapbackup_update_command.adoc[O comando smo backup update]
