---
permalink: unix-administration/task_viewing_clone_split_estimate.html 
sidebar: sidebar 
keywords: clone, split, estimate, help, total, free, space, available, aggregate, amount, space, share, smo 
summary: A estimativa de divisão de clones ajuda você a saber o espaço livre total disponível no agregado, a quantidade de espaço compartilhado entre o clone e o banco de dados original e o espaço usado exclusivamente pelo clone. Além disso, é possível visualizar a data e a hora em que o clone subjacente foi criado e a idade do clone. Com base nessa estimativa, você decide se quer dividir um clone ou não. 
---
= Exibindo uma estimativa de divisão de clones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A estimativa de divisão de clones ajuda você a saber o espaço livre total disponível no agregado, a quantidade de espaço compartilhado entre o clone e o banco de dados original e o espaço usado exclusivamente pelo clone. Além disso, é possível visualizar a data e a hora em que o clone subjacente foi criado e a idade do clone. Com base nessa estimativa, você decide se quer dividir um clone ou não.

Para visualizar a estimativa de divisão de clones, você deve inserir o nome do perfil do clone original e o rótulo ou GUID da operação de clone. Se o clone estiver em um host diferente, você poderá especificar o nome do host.

. Para exibir a estimativa de divisão de clones, digite o seguinte comando:
`smo clone split-estimate -profileprofile [-hosthostname] [-labelclone-label | -idclone-id][-quiet | -verbose]`


O exemplo a seguir mostra o comando para a estimativa de armazenamento dividido clone:

[listing]
----
smo clone split-estimate

-profile p1 -label clone_test_label
----