---
permalink: unix-administration/task_protecting_archive_log_backups.html 
sidebar: sidebar 
keywords: creating, profile, enable, protection, archive, log, backup, base, policy 
summary: Ao criar perfis, você pode ativar a proteção para os backups de log de arquivamento com base na política de proteção de log de arquivamento. 
---
= Proteção dos backups de log de arquivamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao criar perfis, você pode ativar a proteção para os backups de log de arquivamento com base na política de proteção de log de arquivamento.

. Introduza o seguinte comando:
`smo profile create -profileprofile [-profile-passwordprofile_password] -repository-dbnamerepo_dbname-hostrepo_host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host [-siddb_sid] [-login-usernamedb_username-passworddb_password-portdb_port] [-rman {-controlfile | {-login-usernamerman_username-passwordrman_password-tnsnamerman_tnsname} } ] -osaccountosaccount-osgrouposgroup [-retain [-hourly [-countn] [-durationm]] [-daily [-countn] [-durationm]] [-weekly [-countn] [-durationm]] [-monthly [-countn] [-durationm]]] [-commentcomment][-snapname-patternpattern][-protect [-protection-policypolicy_name]] [-summary-notification] [-notification [-success-emailemail_address1, email_address2-subjectsubject_pattern] [-failure-emailemail_address1, email_address2-subjectsubject_pattern]][-separate-archivelog-backups-retain-archivelog-backups-hourshours | -daysdays | -weeksweeks| -monthsmonths [-protect [-protection-policypolicy_name] | -noprotect] [-include-with-online-backups | -no-include-with-online-backups]] [-dump]`
+
|===
| Se... | Então... 


 a| 
*Você deseja fazer backup dos backups de log de arquivamento separadamente e proteger os arquivos de log de arquivamento*
 a| 
Especifique as seguintes opções:

** -separate-archivelog-backups permite que você separe os arquivos de log de arquivo dos arquivos de dados.
** -protect atribui uma política de proteção separada para os backups de log de arquivo de log.
** -protection-policy atribui a política de proteção para os backups de log de arquivo.


|===

