---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_and_assign_a_protection_policy.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, oracle, enable, protect, client, payroll, paydb 
summary: Você deve criar um perfil no SnapManager para Oracle, ativar a proteção no perfil e atribuir uma política de proteção para criar um backup protegido. 
---
= Usando o SnapManager para Oracle para criar o perfil do banco de dados e atribuir uma política de proteção
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve criar um perfil no SnapManager para Oracle, ativar a proteção no perfil e atribuir uma política de proteção para criar um backup protegido.

Um perfil contém informações sobre o banco de dados que está sendo gerenciado, incluindo suas credenciais, configurações de backup e configurações de proteção para backups. Depois de criar um perfil, você não precisa especificar os detalhes do banco de dados sempre que executar uma operação. Um perfil pode referenciar apenas um banco de dados, mas esse mesmo banco de dados pode ser referenciado por mais de um perfil.

. Vá para o cliente SnapManager para Oracle.
. Na árvore Repositories, clique com o botão direito do Mouse no host e selecione *Create Profile*.
. Na página informações de configuração do perfil, insira os detalhes do perfil e clique em *Avançar*.
+
Pode introduzir as seguintes informações:

+
** Nome do perfil: Folha de pagamento_prod2
** Senha do perfil: payroll123
** Comentário: Banco de dados de Folha de pagamento de produção


. Nas páginas informações de configuração de banco de dados, insira os detalhes do banco de dados e clique em *Next*.
+
Pode introduzir as seguintes informações:

+
** Nome do banco de dados: PAYDB
** Banco de dados SID: Payrolldb
** Host do banco de dados: Aceite o padrão. Como você está criando um perfil a partir de um host na árvore do repositório, o SnapManager exibe o nome do host.
** Conta de host, representando a conta de usuário Oracle: oracle
** Grupo anfitrião, representando o grupo Oracle: dba


. Na página informações de conexão de banco de dados, clique em *usar autenticação de banco de dados* para permitir que os usuários se autentiquem usando informações de banco de dados.
. Introduza os detalhes da ligação à base de dados e clique em *seguinte*.
+
Pode introduzir as seguintes informações:

+
** Nome de usuário privilegiado SYSDBA, representando o administrador do banco de dados do sistema que tem Privileges administrativo: Sys
** Senha (senha SYSDBA): oracle
** Porta para conetar ao host de banco de dados: 1521


. Na página informações de configuração do RMAN, clique em *não use RMAN* e clique em *Next*.
+
O Oracle Recovery Manager (RMAN) é uma ferramenta Oracle que ajuda você a fazer backup e recuperar bancos de dados Oracle usando deteção em nível de bloco.

. Na página informações do Nome do Snapshot, especifique uma convenção de nomenclatura para os instantâneos associados a esse perfil selecionando variáveis.
+
A variável smid cria um identificador único de snapshot.

+
Execute o seguinte:

+
.. Na lista Variable Token (Token variável), selecione usertext e clique em *Add* (Adicionar).
.. Digite payroll.techco.com_ como o nome do host e clique em *OK*.
.. Clique em *left* até que o nome do host apareça logo após o smo na caixa Formatar.
.. Clique em *seguinte*.


+
A convenção de nomenclatura Snapshot de smo_hostname_smoprofile_dbsid_scope_mode_smid se torna "smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" (onde "f" indica um backup completo, "a" indica o modo automático e "x" representa o SMID exclusivo).

. Selecione *Política de proteção do Protection Manager*.
+
A *Política de proteção do Gerenciador de proteção* permite que você selecione uma política de proteção que foi configurada usando o Console de Gerenciamento do NetApp.

. Selecione *dados de Folha de pagamento TechCo: Backup* como a política de proteção das políticas de proteção recuperadas do Console de Gerenciamento do NetApp e clique em *Avançar*.
. Na página Executar operação, verifique as informações e clique em *criar*.
. Clique em *Detalhes da operação* para ver informações sobre a operação criar perfil e informações de elegibilidade de restauração baseadas em volume.
+
** A atribuição de uma política de proteção do console de gerenciamento do NetApp ao perfil do banco de dados cria automaticamente um conjunto de dados não conformante, visível para o operador do console de gerenciamento do NetApp, com a convenção de nome smo_<hostname>_<profilename>, ou neste exemplo: smo_payroll.tech.com_PAYDB.
** Se o perfil não for elegível para restauração de volume (também chamado de "restauração rápida"), ocorre o seguinte:
+
*** A guia *Results* indica que a criação do perfil foi bem-sucedida e que os avisos ocorreram durante a operação.
*** A guia *Detalhes da operação* inclui um log DE AVISO, que indica que o perfil não é elegível para restauração rápida e explica por quê.





