---
permalink: unix-administration/task_freeing_backups.html 
sidebar: sidebar 
keywords: free, backup, delete, snapshot, copies, deleting, metadata, function 
summary: Você pode liberar backups, o que exclui as cópias Snapshot sem excluir os metadados do backup. Esta função liberta o espaço ocupado pelo backup. Você pode usar o comando smo backup free para liberar os backups. 
---
= Liberando backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode liberar backups, o que exclui as cópias Snapshot sem excluir os metadados do backup. Esta função liberta o espaço ocupado pelo backup. Você pode usar o comando smo backup free para liberar os backups.

Para que um backup seja qualificado para liberar, você deve garantir o seguinte:

* A cópia de segurança foi bem-sucedida
* A cópia de segurança não deve ser montada
* O backup não tem clones
* O backup não deve ser retido usando uma política de retenção ilimitada
* A cópia de segurança ainda não foi libertada


Se a proteção estiver ativada no perfil e a política de proteção contiver conexões do nó principal que usam uma relação espelhada, as cópias Snapshot serão excluídas no nó primário quando um backup for liberado. Essas cópias Snapshot também são excluídas dos nós espelhados quando a próxima transferência para o storage secundário ocorre.

Quando você libera um backup protegido, o SnapManager solicita que o Gerenciador de proteção remova as cópias Snapshot locais do backup. Se a operação livre de backup for bem-sucedida para os backups protegidos, as cópias Snapshot serão excluídas pelo Protection Manager de maneira assíncrona.

|===
| Estado de proteção | Estado local | Ação no storage primário | Ação no storage secundário | Explicação 


 a| 
Não solicitado (a ser protegido)
 a| 
Existe
 a| 
Liberta a cópia de segurança
 a| 
Nenhuma ação necessária
 a| 
O SnapManager libera o backup local.



 a| 
Libertado
 a| 
Nenhuma ação necessária
 a| 
Nenhuma ação necessária
 a| 
O backup local já está liberado.
 a| 
Não protegido



 a| 
Existe
 a| 
Liberta a cópia de segurança
 a| 
Nenhuma ação necessária
 a| 
O SnapManager libera o backup local, mesmo que não haja cópias no storage secundário.
 a| 
Libertado



 a| 
Nenhuma ação necessária
 a| 
Nenhuma ação necessária
 a| 
O backup local já está liberado.
 a| 
Protegido
 a| 
Existe



 a| 
Liberta a cópia de segurança
 a| 
Nenhuma ação necessária; o backup no secundário permanece
 a| 
O SnapManager libera o backup local. As cópias permanecem no storage secundário.
 a| 
Libertado
 a| 
Nenhuma ação necessária

|===
Você pode especificar a opção -dump como um parâmetro opcional para coletar os arquivos de despejo após a operação livre de backup bem-sucedida ou com falha.

. Digite o seguinte comando: smo backup free -profileprofile_name [data | -archivelogs] | -idID | -all] -force [-dump] [-quiet] [-force] [-force]


*Informações relacionadas*

xref:reference_the_smosmsapbackup_free_command.adoc[O comando smo backup free]
