---
permalink: unix-administration/task_restoring_backups_using_fast_restore.html 
sidebar: sidebar 
keywords: force, snapmanager, oracle, volume-based, snaprestore, restore, process 
summary: Você pode forçar o SnapManager para Oracle a usar o processo SnapRestore baseado em volume em vez de outros processos de restauração, se todas as condições de qualificação obrigatórias de restauração rápida forem atendidas. 
---
= Restaurar backups usando restauração rápida
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode forçar o SnapManager para Oracle a usar o processo SnapRestore baseado em volume em vez de outros processos de restauração, se todas as condições de qualificação obrigatórias de restauração rápida forem atendidas.

Você pode usar o comando backup restore com -fast:  `backup restore -fast [require | override | fallback | off]`

Você pode usar a opção -FAST somente se quiser executar uma restauração completa de um backup completo. A opção -FAST inclui os seguintes parâmetros:

* Exigir: Permite executar uma restauração de volume, se todas as condições de qualificação de restauração obrigatória forem atendidas e não forem encontradas verificações sobráveis.
+
Se você especificar a opção -FAST, mas não especificar nenhum parâmetro para -FAST, o SnapManager usará o parâmetro-require como padrão.

* Substituir: Permite substituir verificações de elegibilidade não obrigatórias e executar a restauração rápida baseada em volume.
* Fallback: Permite restaurar o banco de dados usando qualquer método que o SnapManager determine.
+
Se você não especificar -fast, o SnapManager usará o parâmetro -fallback como padrão.

* Desligado: Permite evitar o tempo necessário para executar todas as verificações de elegibilidade, para executar um processo de restauração baseado em arquivos em vez do processo de restauração rápida.


Se o backup não passar nas verificações obrigatórias de elegibilidade, a restauração rápida não poderá ser concluída com êxito.

O SnapManager executa restaurações rápidas baseadas em volume somente em ambientes baseados em UNIX. O SnapManager não realiza restaurações rápidas no ambiente Windows.

Ao executar o VBSR no backup do arquivo de dados, se os arquivos de dados e os arquivos de log de arquivamento estiverem presentes no mesmo volume e se os arquivos de log de arquivamento não estiverem presentes no sistema de arquivos ativo, a restauração e recuperação do banco de dados serão bem-sucedidos. No entanto, os instantâneos de log de arquivo futuros são excluídos como parte do VBSR, resultando em uma entrada obsoleta do backup de log de arquivamento no repositório.

. Digite o seguinte comando:smo backup restore -profileprofile_name-labellabel-complete-fast require-verbose
+
[listing]
----
smo backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -fast require -verbose
----
. Revise as verificações de qualificação para restauração rápida.
. Se a verificação de elegibilidade determinar que nenhuma verificação obrigatória falhou, se certas condições podem ser substituídas e se você quiser continuar com o processo de restauração, digite o seguinte comando: Backup restore -fast override


*Informações relacionadas*

xref:task_creating_pretask_post_task_and_policy_scripts.adoc[Criando scripts de pré-tarefa, pós-tarefa e política]

xref:concept_variables_available_in_custom_script_for_restore_operation.adoc[Variáveis disponíveis nos scripts de tarefa para a operação de restauração]

xref:task_storing_the_task_scripts.adoc[Armazenando os scripts de tarefa]
