---
permalink: unix-installation-7mode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark 
summary: Informações sobre marcas comerciais 
---
= Informações sobre marcas comerciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp, o logotipo da NetApp , Vá Mais Longe, Mais Rápido, AltaVault, ASUP, AutoSupport, Campaign Express, Cloud ONTAP, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Fitness, Flash Accel, Flash Cache, Flash Pool, FlashRay, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, GetSuccessful, LockVault, Manage ONTAP, Mars, MetroCluster, MultiStore, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, StorageGRID, Tech OnTap, Unbound Cloud e WAFL, entre outros nomes, são marcas comerciais ou marcas registradas da NetApp, Inc., nos Estados Unidos e/ou em outros países. Todas as outras marcas ou produtos são marcas comerciais ou marcas registradas de seus respectivos proprietários e devem ser tratados como tal.  Uma lista atualizada das marcas registradas da NetApp está disponível na web em http://www.netapp.com/us/legal/netapptmlist.aspx[] .
