---
permalink: unix-installation-7mode/task_verifying_the_oracle_listener_configuration.html 
sidebar: sidebar 
keywords: listener, process, client, connection, request, receive, traffic, status 
summary: O ouvinte é um processo que escuta as solicitações de conexão do cliente. Ele recebe solicitações de conexão de cliente recebidas e gerencia o tráfego dessas solicitações para o banco de dados. Antes de se conetar a um banco de dados de destino ou instância de banco de dados de repositório, você pode usar o comando STATUS para verificar a configuração do ouvinte. 
---
= Verificando a configuração do Oracle listener
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ouvinte é um processo que escuta as solicitações de conexão do cliente. Ele recebe solicitações de conexão de cliente recebidas e gerencia o tráfego dessas solicitações para o banco de dados. Antes de se conetar a um banco de dados de destino ou instância de banco de dados de repositório, você pode usar o comando STATUS para verificar a configuração do ouvinte.

O comando STATUS exibe informações básicas de status sobre um ouvinte específico, incluindo um resumo das configurações do ouvinte, endereços de protocolo de escuta e um resumo dos serviços registrados nesse ouvinte.

. Digite o seguinte comando no prompt de comando: 'LSNRCTL STATUS'
+
O valor padrão atribuído à porta do ouvinte é 1521.


