---
permalink: unix-installation-7mode/task_accessing_the_snapmanager_user_interface.html 
sidebar: sidebar 
keywords: access, snapmanager, user, interface, ui, remote, web, browser, system, database, smogui 
summary: 'Você pode acessar a interface de usuário (UI) do SnapManager remotamente usando um navegador da Web de qualquer sistema executado em um sistema operacional suportado pelo SnapManager. Você também pode acessar a IU do SnapManager a partir do host do banco de dados de destino executando o comando smogui.' 
---
= Acessando a interface do usuário do SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode acessar a interface de usuário (UI) do SnapManager remotamente usando um navegador da Web de qualquer sistema executado em um sistema operacional suportado pelo SnapManager. Você também pode acessar a IU do SnapManager a partir do host do banco de dados de destino executando o comando smogui.

* Você deve garantir que o SnapManager esteja em execução.
* Você deve garantir que o sistema operacional suportado e o Java estejam instalados no sistema onde deseja acessar a IU do SnapManager.
+
Para obter informações sobre o sistema operacional suportado e Java, consulte a ferramenta Matriz de interoperabilidade.

+
.. Na janela do navegador da Web, digite o seguinte: https://server_name.domain.com:port_number[]
+
*** Server_name é o nome do host de banco de dados de destino onde o SnapManager está instalado.
+
Você também pode inserir o endereço IP do host do banco de dados de destino.

*** Port_Number é a porta na qual o SnapManager está sendo executado.
+
O valor padrão é 27214.



.. Clique no link.
+
A UI é exibida.




